name: cd

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      image_version:
        description: 'The beta image to push'
        required: false
        default: 'none'
  release:
    types: [created]

env:
  IMAGE_NAME: authzen-todo-backend
  VAULT_ADDR: https://vault.eng.aserto.com/

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        id: get_version
        run: |
          EVENT_NAME=${{ github.event_name }}
          IS_GITHUB_TAG=${{ startsWith(github.ref, 'refs/tags/v') }}
          if [[ $EVENT_NAME == 'release' && $IS_GITHUB_TAG == 'true' ]]; then
            IMAGE_VERSION=${GITHUB_REF/refs\/tags\/v/}
          else
            IMAGE_VERSION=${{ github.event.inputs.image_version }}
          fi
          echo "using version: $IMAGE_VERSION"
          echo ::set-output name=VERSION::$IMAGE_VERSION

      - name: Read Configuration
        uses: hashicorp/vault-action@v2.5.0
        id: vault
        with:
          url: https://vault.eng.aserto.com/
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/github  "SSH_PRIVATE_KEY"     | SSH_PRIVATE_KEY;
            kv/data/github  "READ_WRITE_TOKEN"    | READ_WRITE_TOKEN;

      - uses: actions/checkout@v2

      - name: Setup git
        run: |
          mkdir -p $HOME/.ssh
          umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf https://github.com/
          git config --global user.email "github-bot@aserto.com"
          git config --global user.name "Aserto Bot"
      - name: Checkout kube-play
        uses: actions/checkout@master
        with:
          repository: aserto-dev/kube-play
          fetch-depth: '0'
          ref:  ${{ startsWith(github.ref, 'refs/tags/v') && 'refs/heads/main' || 'refs/heads/beta' }}
          path: kube-play
          # github personal access token, for pushing commits
          token: ${{ steps.vault.outputs.READ_WRITE_TOKEN }}

      - name: Update version
        uses: mikefarah/yq@v4.6.1
        with:
          cmd:  yq eval --inplace '.spec.template.spec.containers[0].image = "ghcr.io/aserto-dev/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}"' ./kube-play/demo-authzen-todo-backend/templates/deployment.yaml

      - name: Commit and push
        id: push
        run: |
          cd kube-play
          git add .
          git commit -m "update authzen-todo-backend"
          git push
